# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(628, 511)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plotWindow = QtWidgets.QWidget(Dialog)
        self.plotWindow.setObjectName("plotWindow")
        self.plotLayout = QtWidgets.QVBoxLayout(self.plotWindow)
        self.plotLayout.setObjectName("plotLayout")
        self.verticalLayout_2.addWidget(self.plotWindow)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.plotWindow2 = QtWidgets.QWidget(Dialog)
        self.plotWindow2.setObjectName("plotWindow2")
        self.plotLayout2 = QtWidgets.QVBoxLayout(self.plotWindow2)
        self.plotLayout2.setObjectName("plotLayout2")
        self.verticalLayout_2.addWidget(self.plotWindow2)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Выбор данных ( без шума )"))
        self.pushButton_2.setText(_translate("Dialog", "Выбор данных ( с шумом )"))
